import React, { Fragment } from "react";

export const About = () => (
    <Fragment>
        <h1>About</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quos vero quo iste dolor eligendi dignissimos quidem earum dolore delectus libero perferendis, eos sequi corrupti nesciunt ullam soluta qui sunt repudiandae natus similique a sit nobis. Rerum aliquam tenetur in illum voluptatum nobis aliquid dolorem mollitia esse, cum distinctio, repellendus non nihil consectetur quibusdam ad soluta obcaecati illo delectus, unde magnam! Consectetur cupiditate aliquam sed, voluptate consequatur vero odit quasi quisquam magnam animi sequi! Sed aliquam dolor tenetur excepturi distinctio? Necessitatibus doloribus vero debitis optio voluptate, iure reiciendis. Totam eligendi debitis possimus omnis. Reiciendis est magni inventore blanditiis itaque nihil quo reprehenderit perferendis neque fuga veritatis atque suscipit, quisquam corporis sequi eveniet eligendi fugiat quia quaerat provident amet laborum sed rerum quasi? Facere, iste? Error voluptas debitis et ut perferendis tempore modi hic suscipit maxime quaerat eaque quas enim magnam provident illo, quo molestias neque laudantium quidem distinctio voluptatum eligendi consequatur atque praesentium! Hic blanditiis culpa repellendus similique quasi excepturi cupiditate modi tenetur neque molestias? Dolorem explicabo suscipit, numquam, voluptate non laborum eveniet possimus rem similique illo alias eaque rerum maiores sequi itaque. Ea, quia quis rem totam veritatis ipsam ducimus qui, assumenda illum excepturi recusandae vitae laborum modi ratione beatae porro iure consequuntur soluta consectetur numquam nostrum voluptatum. Laudantium, atque. Quas ipsa minima aperiam provident consequatur? Eum minima deserunt perferendis beatae necessitatibus maxime excepturi explicabo inventore dignissimos. Praesentium incidunt, consectetur dolorem porro doloribus at iste error alias nemo rerum, voluptatem nihil in. Necessitatibus cupiditate repudiandae assumenda sint exercitationem tempore, culpa recusandae distinctio obcaecati nihil pariatur consequatur inventore provident fugiat qui eius quibusdam at ut natus asperiores earum autem rem. At sunt nihil quis veniam, molestias optio accusantium nemo eaque nam laborum ipsa. Ducimus corrupti impedit quibusdam ipsam dicta, sunt facilis neque voluptatum sint eum odio aliquam eos voluptates nesciunt!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa aperiam quas ducimus aliquid quidem quia alias magni dolorum natus, ea saepe dolores quod maxime enim. Assumenda nam libero quod quasi veniam sequi voluptatum aperiam dolore numquam culpa, nisi nihil corrupti ducimus iusto hic distinctio. Nam a et voluptas quae temporibus magni odit suscipit. Commodi minus praesentium veniam ad facere perspiciatis rem enim consequuntur sequi porro sint explicabo suscipit, quod dolorem iusto officiis minima tempore non reprehenderit aut! Consequatur quaerat non dolorem nam omnis in dolor, minus reiciendis, neque et aliquam ullam voluptatum molestias veritatis incidunt odio ducimus harum, quidem cumque?</p>

    </Fragment>
);